// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)
import HelloController from "./hello_controller"
application.register("hello", HelloController)
import LanguageToggleController from "./language_toggle_controller"
application.register("language-toggle", LanguageToggleController)
import KpiController from "./kpi_controller"
application.register("kpi", KpiController)
import WizardController from "./wizard_controller"
application.register("wizard", WizardController)
import LeanCanvasController from "./lean_canvas_controller"
application.register("lean-canvas", LeanCanvasController)
import WizardProgressController from "./wizard_progress_controller"
application.register("wizard-progress", WizardProgressController)
